version: "3.8"
services:
  app:
    build: ./build_app
    ports:
      - "8080:8000"
    networks:
      pyAPI:
        ipv4_address: 10.0.0.2
    depends_on:
      - db
    links:
      - db
    volumes:
      - pyAPI_app_data:/home/src/
  db:
    build: ./build_db
    networks:
      pyAPI:
        ipv4_address: 10.0.0.3
    volumes:
      - pyAPI_mysql_data:/var/lib/mysql
networks:
  pyAPI:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
volumes:
  pyAPI_mysql_data:
  pyAPI_app_data:
